config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello', to: 'welcome#hello'
  resources :calculations
  resources :categories
  root to: redirect('/calculations')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord

    OPERANDS = ['+', '-', '*', '/']


    belongs_to :category


    validates :argument1, :argument2, :operand,
        presence: true
    validates :operand, inclusion: {in: OPERANDS}

    def frontend_title

        title.presence || "#{argument1} #{operand} #{argument2}"


    end

    def result
        case operand
        when '+' then argument1 + argument2
        when '-' then argument1 - argument2
        when '*' then argument1 * argument2
        when '/' then 
        else "dunno!"
        end

    end
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :calculations

    validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
    def index
        @calculations = Calculation.all
        respond_to do |format|
        	format.json {
        		render json: @calculations.to_json
        	}
        	format.xml {
        		render xml: @calculations.to_xml
        	}
        	format.html{
        		render 'index'
        	}
        end
    end

    def show
        @calculation = Calculation.find(params[:id])
    end

    def new
        @calculation = Calculation.new
    end

    def create
        @calculation = Calculation.new(calculation_params)
        if @calculation.operand == '/' && @calculation.argument2 ==0
            flash[:error] = "argument2 is wrong please try  another one different to 0"
            render 'new'
        else
            
            if @calculation.save
                flash[:success] = "Successfully created!"
                redirect_to calculation_path(@calculation)
            else
                flash[:error] = "could not create!"
                render 'new'
            end
        end
    end

    def edit
        @calculation = Calculation.find(params[:id])
        
    end

    def update
        @calculation = Calculation.find(params[:id])

        if @calculation.update(calculation_params)
            redirect_to calculation_path(@calculation)
            flash[:success] = "Successfully update!"
            else
                flash[:error] = "could not update"
                render 'edit'
            end
        
    end

    def destroy
        @calculation = Calculation.find(params[:id])
        @calculation.destroy
        redirect_to calculations_path
    end
    private def calculation_params
        params.require(:calculation).permit(:argument1, :operand, :argument2, :title, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)    
        if @category.save
            flash[:success] = "Successfully created!"
            redirect_to category_path(@category)
        else
            flash[:error] = "could not create!"
            render 'new'
        end
    
    
    end

    def edit
        @Category = Category.find(params[:id])
        
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            redirect_to category_path(@category)
            flash[:success] = "Successfully update!"
            else
                flash[:error] = "could not update"
                render 'edit'
            end
        
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_path
    end
    private def category_params
        params.require(:category).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def hello
        @count = params[:count].to_i
        @count = 1 if @count.zero?
        @time = Time.new.to_s
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculations/_form.html.slim
- if !@calculation.errors
    ul
        -@calculation.errors.full_messages.each do |msg|

          li = msg

= simple_form_for @calculation do |f|
    .row
        .col-sm-8 = f.input :title
        .col-sm-4 = f.association :category
    .row
        .col-sm-4 = f.input :argument1
        .col-sm-2 = f.input :operand, as: :select, collection: Calculation::OPERANDS
        .col-sm-4 = f.input :argument2
        .col-sm-2 
            .form-group
                .form-label
                    | &nbsp
                = f.submit class: 'btn btn-primary form-control'

/    .form-group
        = f.label :argument1, class: 'form-label'
        = f.text_field :argument1, class: 'form-control'
    

    p
        = f.label :operand
        = f.select :operand, Calculation::OPERANDS
    

    p
        = f.label :argument2
        = f.text_field :argument2
    = f.submit

/css:
    .field_with_errors {
        outline: 1px solid red;
    }

app/views/calculations/edit.html.slim
h1 Edit Calculation

= render 'form'

app/views/calculations/index.html.slim
h1 = t('.all_calculations')

p   = t('.its_so_many', count: @calculations.count) 

-if @calculations.present?
    table.table
        thead
            tr
                th = Calculation.human_attribute_name(:title)
                th = Calculation.human_attribute_name(:argument1)
                th Operation
                th Operand 2
                th
        tbody
            -@calculations.each do |calculation|
                tr
                    td = calculation.title
                    td = calculation.argument1
                    td = calculation.operand
                    td = calculation.argument2
                    td
                        a.btn.btn-primary href = calculation_path(calculation)
                            | Show
                        a.btn.btn-secondary< href = edit_calculation_path(calculation)
                            | Edit
                        a.btn.btn-danger< href = calculation_path(calculation) data-method="delete" data-confirm="really delete?"
                            | Delete
-else
    p There are no calculation

=link_to "New Calculation", new_calculation_path, class: 'btn btn-success'

app/views/calculations/new.html.slim
h1 New Calculation

= render 'form'

app/views/calculations/show.html.slim
h1 = @calculation.title

-   if @calculation.category
    a href=category_path(@calculation.category)
        | >>
        =< @calculation.category.title

h3
    => @calculation.argument1
    = @calculation.operand
    =<> @calculation.argument2
    | =
    =< @calculation.result
= link_to "back", calculations_path

app/views/categories/_form.html.slim
= simple_form_for @category do |f|
    = f.input :title
    = f.submit

app/views/categories/index.html.slim
h1 Categories

-   if @categories.present?
    .list-group
        -@categories.each do |category|
            .list-group-item
                span = category.title
                .badge.bg-secondary = category.calculations.size
                .float-end
                    a.btn.btn-primary.btn-sm> href=edit_category_path(category)
                        | Edit
                    a.btn.btn-success.btn-sm href=category_path(category)
                        | Show
-   else
    .alert.alert-danger No Categories

a.btn.btn-success href=new_category_path
    | + Add Category

app/views/categories/new.html.slim
h1 New Category

= render 'form'

app/views/categories/show.html.slim
h1 = @category.title

- if @category.calculations.present?
    ul.list-group
       - @category.calculations.each do |calculation|
            a.list-group-item href=calculation_path(calculation)
                = calculation.frontend_title
-else
    .alert.alert-danger No calculations here!

a href = categories_path << back

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title Calculette
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags 
    = csp_meta_tag 
    
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' 


  body
    header
      #navbarHeader.collapse.bg-dark
        .container
          .row
            .col-sm-8.col-md-7.py-4
              h4.text-white About
              p.text-muted Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.
            .col-sm-4.offset-md-1.py-4
              h4.text-white Contact
              ul.list-unstyled
                li
                  a.text-white href="#"  Follow on Twitter
                li
                  a.text-white href="#"  Like on Facebook
                li
                  a.text-white href="#"  Email me
      .navbar.navbar-dark.bg-dark.shadow-sm
        .container
          a.navbar-brand.d-flex.align-items-center href="#" 
            svg.me-2 aria-hidden="true" fill="none" height="20" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="20" xmlns="http://www.w3.org/2000/svg" 
              path d=("M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z") 
              circle cx="12" cy="13" r="4" 
            strong Album
          button.navbar-toggler aria-controls="navbarHeader" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarHeader" data-bs-toggle="collapse" type="button" 
            span.navbar-toggler-icon
    main
      section.container
          - flash.each do |status, msg| 
            div class="flash-#{status}"
              = msg 
 
          = yield 

app/views/welcome/hello.html.erb
<h1>Hello</h1>
<% @count.times do %>
<p>Hi folks, it's <%= @time %>.</p>
<% end %>